spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/media_task
spring.datasource.username=media
spring.datasource.password=media
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
