package com.ryan.media.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Exposes Week17 Mainbase model-race and repair seed payloads.
 *
 * This controller intentionally reads committed artifact payloads instead of
 * returning hand-written mock data. The payloads are generated by Mainbase from:
 * DSS -> control candidate -> event-window ranking -> repair closure.
 */
@RestController
public class Week17ModelRaceSeedController {

    private static final Path MODEL_RACE_PAYLOAD = Path.of(
        "artifacts",
        "manifests",
        "week17_model_race_seed",
        "mainbase_model_race_seed_payload.json"
    );

    private static final Path REPAIR_PAYLOAD = Path.of(
        "artifacts",
        "manifests",
        "week17_model_race_seed",
        "mainbase_repair_seed_payload.json"
    );

    private static final Path INGESTION_SUMMARY = Path.of(
        "artifacts",
        "manifests",
        "week17_model_race_seed",
        "java_payload_ingestion_summary.json"
    );

    private final ObjectMapper objectMapper;

    public Week17ModelRaceSeedController(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @GetMapping("/api/week17/model-race-seed")
    public ResponseEntity<JsonNode> modelRaceSeed() throws IOException {
        return readJsonPayload(MODEL_RACE_PAYLOAD);
    }

    @GetMapping("/api/week17/repair-seed")
    public ResponseEntity<JsonNode> repairSeed() throws IOException {
        return readJsonPayload(REPAIR_PAYLOAD);
    }

    @GetMapping("/api/week17/model-race-seed/summary")
    public ResponseEntity<JsonNode> modelRaceSeedSummary() throws IOException {
        return readJsonPayload(INGESTION_SUMMARY);
    }

    private ResponseEntity<JsonNode> readJsonPayload(Path path) throws IOException {
        if (!Files.exists(path)) {
            return ResponseEntity.notFound().build();
        }
        return ResponseEntity.ok(objectMapper.readTree(path.toFile()));
    }
}